image: docker:latest
services:
  - docker:dind

stages:
  - build
  - push

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build:
  stage: build

  script:
    - docker info
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE
    - docker tag $IMAGE "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

push_dev:
    stage: push
    script:
        - docker pull $IMAGE
        - docker tag $IMAGE "$CI_REGISTRY_IMAGE:dev"
        - docker push "$CI_REGISTRY_IMAGE:dev"
    only:
        - develop
    
push_master:
    stage: push
    script:
        - docker pull $IMAGE
        - docker tag $IMAGE "$CI_REGISTRY_IMAGE:latest"
        - docker push "$CI_REGISTRY_IMAGE:latest"
    only:
        - master
